# Generated by Django 5.1.1 on 2024-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luwasapp', '0002_department_respondentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='respondents',
            field=models.ManyToManyField(related_name='departments', to='luwasapp.respondentprofile'),
        ),
    ]
