# Generated by Django 5.1.1 on 2024-11-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luwasapp', '0004_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='respondents',
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='luwasapp.department'),
        ),
    ]
