# Generated by Django 5.1.1 on 2024-11-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luwasapp', '0005_remove_department_respondents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentprofile',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='luwasapp.establishment'),
        ),
    ]
