# Generated by Django 5.1.1 on 2024-11-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luwasapp', '0008_alter_incidentreport_respondent_user_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='respondent',
        ),
        migrations.CreateModel(
            name='IncidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_sent', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='luwasapp.incidentreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
