# Generated by Django 5.1.1 on 2024-11-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luwasapp', '0009_remove_incidentreport_respondent_incidentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('medical_emergency', 'Medical Emergency'), ('fire_incident', 'Fire Incident'), ('road_accident', 'Road Accident'), ('natural_disaster', 'Natural Disaster'), ('crime_related', 'Crime Related'), ('domestic_violence', 'Domestic Violence'), ('psychological_crisis', 'Psychological Crisis'), ('missing_person', 'Missing Person'), ('poisoning', 'Poisoning'), ('gas_leak', 'Gas Leak'), ('electrical_hazard', 'Electrical Hazard'), ('hazardous_materials', 'Hazardous Materials Spill'), ('flooding', 'Flooding'), ('earthquake', 'Earthquake'), ('typhoon', 'Typhoon'), ('animal_attack', 'Animal Attack'), ('terrorist_threat', 'Terrorist Threat/Attack'), ('building_collapse', 'Building Collapse'), ('public_disturbance', 'Public Disturbance'), ('child_abuse', 'Child Abuse'), ('elderly_abuse', 'Elderly Abuse')], default='medical_emergency', max_length=255),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=255),
        ),
    ]
