# Generated by Django 5.1.1 on 2024-11-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luwasapp', '0011_incidentreport_latitude_incidentreport_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='department',
        ),
    ]
