# Generated by Django 5.1.1 on 2024-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luwasapp', '0013_alter_incidentreport_status_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(blank=True, choices=[('reported', 'Reported'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=255),
        ),
    ]
